platform :ios, '13.0'
source 'https://github.com/CocoaPods/Specs.git'
workspace '../../AdbidSDKWorkspace.xcworkspace'

target 'AdbidSDKDemo' do
  use_frameworks!
  
  pod 'AdbidSDK','2.1.1.11'
  pod 'LeadmoadAdSDK', "1.0.25"
  pod 'UBiXMerakSDK', "2.10.2"
  pod 'FunlinkSDK','2.9.0.0.7'
  
end
