platform :ios, '13.0'
source 'https://github.com/CocoaPods/Specs.git'
workspace '../../AdbidSDKWorkspace.xcworkspace'

target 'AdbidSDKDemo' do
  use_frameworks!
  
  pod 'AdbidSDK','2.1.1.3'
  pod 'LeadmoadAdSDK', "1.0.19"
  pod 'UBiXMerakSDK', "2.10.0.11"
  
end
