platform :ios, '13.0'
source 'https://github.com/CocoaPods/Specs.git'
workspace '../../AdbidSDKWorkspace.xcworkspace'

target 'AdbidSDKDemo' do
  use_frameworks!
  
  pod 'AdbidSDK','2.1.0.12'
  pod 'GDTMobSDK','4.15.70'
  pod 'KSAdSDK','4.12.20.1'
  
end
